github.dismiss_out_of_range_messages

checkstyle_format.base_path = Dir.pwd
report_files = Dir.glob("app/build/reports/detekt/detekt.xml")
message('test1')
for report_file in report_files do
    message('test2')
    checkstyle_format.report report_file
end
    message('test3')
