on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      # detekt チェック開始
      - name: Lint with detekt
        run: ./gradlew detekt

      # detekt 結果ファイルをArtifactにアップロード
      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: detekt_results
          path: |
            **/build/reports/detekt/*
          if-no-files-found: error
          retention-days: 14

      # danger でレビューコメント
      - uses: MeilCli/danger-action@v5
        name: Run Danger
        with:
          plugins_file: '.github/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: '.github/Dangerfile'
          danger_id: 'danger-detekt'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}